[build]
  base = "/"
  publish = "dist"
  command = "mkdir -p dist/node_modules/@fortawesome && npm ci && cp -r index.html styles.css VotingApp.js demo-data.js src dist/ && cp -r node_modules/@fortawesome dist/node_modules/@fortawesome"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[context.production]
  command = "mkdir -p dist/node_modules/@fortawesome && npm ci && cp -r index.html styles.css VotingApp.js demo-data.js src dist/ && cp -r node_modules/@fortawesome dist/node_modules/@fortawesome"

[context.deploy-preview]
  command = "mkdir -p dist/node_modules/@fortawesome && npm ci && cp -r index.html styles.css VotingApp.js demo-data.js src dist/ && cp -r node_modules/@fortawesome dist/node_modules/@fortawesome"

[context.branch-deploy]
  command = "mkdir -p dist/node_modules/@fortawesome && npm ci && cp -r index.html styles.css VotingApp.js demo-data.js src dist/ && cp -r node_modules/@fortawesome dist/node_modules/@fortawesome"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true

# Enable Deploy Previews
[context.deploy-preview.environment]
  NODE_ENV = "preview"

# Enable Branch Deploys
[context.branch-deploy.environment]
  NODE_ENV = "development"
